# Generated by Django 5.2.11 on 2026-02-04 14:08

import django.core.validators
import speakproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakproject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="account_holder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="account_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="ifsc_code",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid IFSC code",
                        regex="^[A-Z]{4}0[A-Z0-9]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="upi_id",
            field=models.CharField(
                blank=True,
                max_length=320,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid UPI ID",
                        regex="^[\\w.\\-]{2,256}@[a-zA-Z]{2,64}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="medical_document",
            field=models.FileField(upload_to=speakproject.models.pdf_only),
        ),
    ]
