# Generated by Django 6.0.2 on 2026-04-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='razorpay_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
