# Generated by Django 5.2.11 on 2026-02-04 15:15

import speakproject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakproject", "0002_employeeprofile_account_holder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="image_hash",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_images/",
                validators=[speakproject.models.jpg_only],
            ),
        ),
    ]
