# Generated by Django 6.0.2 on 2026-04-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0002_profile_razorpay_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
