# Generated by Django 6.0.2 on 2026-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0003_booking_original_amount_booking_original_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
