# Generated by Django 5.2.11 on 2026-02-10 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speakproject", "0003_employeeprofile_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_booked", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="speakproject.employeeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
                "unique_together": {("employee", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount", models.PositiveIntegerField(default=30)),
                ("duration_minutes", models.PositiveIntegerField(default=10)),
                ("payment_gateway", models.CharField(max_length=30)),
                ("payment_id", models.CharField(max_length=200)),
                (
                    "invoice_pdf",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_refunded", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="speakproject.employeeprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="speakproject.userprofile",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="speakproject.employeeslot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
