# Generated by Django 6.0.2 on 2026-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0005_profile_avg_rating_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_paid',
            field=models.BooleanField(default=False),
        ),
    ]
