# Generated by Django 6.0.2 on 2026-04-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0006_booking_advance_paid_booking_remaining_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
