# Generated by Django 6.0.2 on 2026-04-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0007_booking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
