# Generated by Django 6.0.2 on 2026-04-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0008_slot_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='advance_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remaining_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='remaining_paid',
        ),
    ]
