# Generated by Django 6.0.2 on 2026-04-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0009_remove_booking_advance_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('NG', 'Nigeria'), ('ET', 'Ethiopia')], default='IN', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payout_upi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
