# Generated by Django 6.0.2 on 2026-04-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0010_profile_bank_code_profile_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('NG', 'Nigeria')], default='IN', max_length=5),
        ),
    ]
