# Generated by Django 6.0.2 on 2026-04-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0011_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_done',
            field=models.BooleanField(default=False),
        ),
    ]
