# Generated by Django 6.0.2 on 2026-04-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0012_booking_payout_date_booking_payout_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='original_currency',
        ),
    ]
