# Generated by Django 6.0.2 on 2026-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0013_remove_booking_original_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
