# Generated by Django 6.0.2 on 2026-04-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakproject', '0014_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
